import {
  DurableObjectNamespace,
  D1Database,
  KVNamespace,
  ExecutionContext,
} from "@cloudflare/workers-types";
import { GameDO } from "./durable-objects/GameDO";

export interface Env {
  GAME_DO: DurableObjectNamespace;
  DB: D1Database;
  OPENINGS_KV: KVNamespace;
  GEMINI_API_KEY: string;
  ASSETS: any; // Next.js static assets from @cloudflare/next-on-pages
}

export { GameDO } from "./durable-objects/GameDO";

// Import Next.js worker
// @ts-ignore - This will be generated by @cloudflare/next-on-pages
import nextOnPagesHandler from "../../.vercel/output/static/_worker.js";

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    try {
      const url = new URL(request.url);
      const path = url.pathname;

      // Handle API routes from our custom Worker
      if (path.startsWith("/api/")) {
        // Extract the game ID from the path, e.g., /api/game/{gameId}/move
        const pathSegments = path.split("/");
        const gameIdIndex = pathSegments.indexOf("game") + 1;

        if (gameIdIndex > 0 && gameIdIndex < pathSegments.length) {
          const gameId = pathSegments[gameIdIndex];
          const doId = env.GAME_DO.idFromName(gameId);
          const stub = env.GAME_DO.get(doId);

          // Reconstruct the request URL to be relative for the DO
          const newPath = "/" + pathSegments.slice(gameIdIndex + 1).join("/");
          const newUrl = new URL(request.url);
          newUrl.pathname = newPath;

          const newRequest = new Request(newUrl.toString(), request);
          return await stub.fetch(newRequest as any) as unknown as Response;
        }
      }

      // For all other routes, use Next.js handler
      return await nextOnPagesHandler.fetch(request, env, ctx);
    } catch (error) {
      console.error("Error in fullstack worker:", error);

      // If Next.js handler fails, provide helpful error
      if (error instanceof Error && error.message.includes("Cannot find module")) {
        return new Response(
          "Next.js worker not built yet. Please run: npm run build:next",
          { status: 500 }
        );
      }

      return new Response("Internal Server Error", { status: 500 });
    }
  },
};
